apiVersion: v1
kind: Secret
metadata:
  name: zerossl
data:
  secret: R3hmY1hXQW1vcVlUd19BZllRWFZsY0tEUUlZZ1hjUS03Um0wT3dJZ1JCQzBnemIwUGh1aFZKaFpVdFNjd1VCckN5N1B0c2FRRTA4SHJNY3kwY1NJMGc=
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: zerossl
spec:
  acme:
    email: mail@rolder.ru
    server: https://acme.zerossl.com/v2/DV90
    privateKeySecretRef:
      name: issuer-account-key
    externalAccountBinding:
      keyID: EH8B8zi15632vTOvZt-CbQ
      keySecretRef:
        name: zerossl
        key: secret
    solvers:
    - http01:         
        ingress:
          class: traefik