name: Deploy docs
 
on:
  push:
    branches: ["releases/v0.28.0"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest    
 
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
 
      - uses: pnpm/action-setup@v2
        with:
          version: 6
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install
 
      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: apps/docs/doc_build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/docs/doc_build